const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const root=path.resolve(__dirname,'..'),manifest=JSON.parse(fs.readFileSync(path.join(root,'manifest.webmanifest'),'utf8'));
assert.equal(manifest.display,'standalone');assert.equal(manifest.scope,'./');assert.equal(manifest.start_url,'./');assert.equal(new URL(manifest.start_url,'https://haider1381.github.io/al-marja3/').pathname,'/al-marja3/');
for(const icon of manifest.icons){const b=fs.readFileSync(path.join(root,icon.src));assert.equal(b.subarray(1,4).toString(),'PNG');const [width,height]=icon.sizes.split('x').map(Number);assert.equal(b.readUInt32BE(16),width);assert.equal(b.readUInt32BE(20),height);}
const events={},deleted=[],fetched=[],cached=[];const origin='https://haider1381.github.io',offline={marker:'offline'};
const context=vm.createContext({URL,Set,Response,self:{location:{href:origin+'/al-marja3/sw.js'},clients:{claim:async()=>{}},addEventListener:(name,fn)=>events[name]=fn},caches:{open:async()=>({addAll:async urls=>cached.push(...urls),put:async()=>{}}),keys:async()=>['medbrain-pwa-old','unrelated-app-cache','medbrain-pwa-v1'],delete:async name=>deleted.push(name),match:async()=>offline},fetch:async(request,options)=>{fetched.push({request,options});return {ok:true,type:'basic',clone:()=>({})};}});
vm.runInContext(fs.readFileSync(path.join(root,'sw.js'),'utf8'),context);
(async()=>{let wait;events.install({waitUntil:p=>wait=p});await wait;assert.equal(cached.length,5);assert(cached.every(u=>u.startsWith(origin+'/al-marja3/')));assert(!cached.some(u=>u.endsWith('index.html')||u.endsWith('/')));
events.activate({waitUntil:p=>wait=p});await wait;assert.deepEqual(deleted,['medbrain-pwa-old']);
const dispatch=(url,method='GET',mode='cors')=>{let result;events.fetch({request:{url,method,mode},respondWith:p=>result=p});return result;};
for(const [url,method] of [['https://wuvzteosknrzddsaexez.supabase.co/rest/v1/lectures','GET'],['https://wuvzteosknrzddsaexez.supabase.co/auth/v1/token','POST'],['https://wuvzteosknrzddsaexez.supabase.co/storage/v1/object/sign/lecture-files/a.pdf?token=private','GET'],['https://wuvzteosknrzddsaexez.supabase.co/functions/v1/medbrain-ai','POST'],[origin+'/another-project/index.html','GET'],[origin+'/al-marja3/assets/app-icon-192.png?token=private','GET'],[origin+'/al-marja3/private.pdf','GET']])assert.equal(dispatch(url,method),undefined);
const navigation=await dispatch(origin+'/al-marja3/?code=oauth-return','GET','navigate');assert(navigation.ok);assert.equal(fetched[0].options.cache,'no-cache');context.fetch=async()=>{throw Error('offline');};assert.equal(await dispatch(origin+'/al-marja3/','GET','navigate'),offline);
assert.equal(await dispatch(origin+'/al-marja3/assets/app-icon-192.png'),offline);
console.log('PASS: scoped install manifest, valid PNG sizes, public-only caching, private API/PDF bypass, fresh navigation, offline fallback and isolated cache cleanup');})().catch(e=>{console.error(e);process.exit(1)});